# Generated by Django 5.2 on 2025-05-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_testresult_total_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='total_questions',
        ),
        migrations.AddField(
            model_name='testresult',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
