# Generated by Django 5.2 on 2025-05-13 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_achievement_question_answer_test_question_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='school_class',
            field=models.CharField(choices=[('1А', '1А'), ('1Б', '1Б'), ('1В', '1В'), ('2А', '2А'), ('2Б', '2Б'), ('2В', '2В')], default='1А', max_length=10),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
