# Generated by Django 5.2 on 2025-05-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_school_class_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Учитель')], default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teacher_classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='users.schoolclass'),
        ),
    ]
