# Generated by Django 5.2 on 2025-05-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_is_staff_customuser_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
