# Generated by Django 5.2 on 2025-05-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_testresult_total_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='total_questions',
            new_name='grade',
        ),
    ]
